[package]
name = "onepassword-sys"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "sync"]
sync = ["pollster"]
async = []
std = []

[dependencies]
byteorder = { workspace = true }
preinterpret = { workspace = true }

pollster = { workspace = true, optional = true }
